# Please see the documentation for all configuration options:
# https://help.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: monthly

  - package-ecosystem: npm
    directory: "/docs"
    schedule:
      interval: monthly
    # DevRel should review docs updates
    assignees:
      - "julienrbrt"

  - package-ecosystem: gomod
    directory: "/"
    schedule:
      interval: monthly
    labels:
      - "A:automerge"
      - dependencies
  - package-ecosystem: gomod
    directory: "/simapp"
    schedule:
      interval: monthly
    labels:
      - "A:automerge"
      - dependencies
  - package-ecosystem: gomod
    directory: "/tests"
    schedule:
      interval: monthly
    labels:
      - "A:automerge"
      - dependencies
  - package-ecosystem: gomod
    directory: "/api"
    schedule:
      interval: monthly
    labels:
      - "A:automerge"
      - dependencies
  - package-ecosystem: gomod
    directory: "/orm"
    schedule:
      interval: monthly
    labels:
      - "A:automerge"
      - dependencies
  - package-ecosystem: gomod
    directory: "/core"
    schedule:
      interval: monthly
    labels:
      - "A:automerge"
      - dependencies
  - package-ecosystem: gomod
    directory: "/tools/cosmovisor"
    schedule:
      interval: monthly
    labels:
      - "A:automerge"
      - dependencies
  - package-ecosystem: gomod
    directory: "/depinject"
    schedule:
      interval: monthly
    labels:
      - "A:automerge"
      - dependencies
  - package-ecosystem: gomod
    directory: "/errors"
    schedule:
      interval: monthly
    labels:
      - "A:automerge"
      - dependencies
  - package-ecosystem: gomod
    directory: "/math"
    schedule:
      interval: monthly
    labels:
      - "A:automerge"
      - dependencies
  - package-ecosystem: gomod
    directory: "/client/v2"
    schedule:
      interval: monthly
    labels:
      - "A:automerge"
      - dependencies
  - package-ecosystem: gomod
    directory: "/tx"
    schedule:
      interval: monthly
    labels:
      - "A:automerge"
      - dependencies
  - package-ecosystem: gomod
    directory: "/tools/rosetta"
    schedule:
      interval: monthly
    labels:
      - "A:automerge"
      - dependencies
